name: Deploy to preview channel

on:
  pull_request:
    paths:
      - "docs/**" # run only for specific files

jobs:
  build_and_deploy:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build site
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EZQUAKE_COM }}"
          projectId: ezquake-com
