name: Update ezQuake help files

on:
  workflow_dispatch: # allow manually triggered runs
  repository_dispatch:
    types: [ ezquake-source-updated ]

jobs:
  update_help_files:
    name: Update ezQuake data files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }} # required in order to trigger deploy prod workflow

      - name: Delete existing help files
        run: rm data/ezquake/*.json

      - name: Download help files from ezquake-source
        run: wget -i data/ezquake/files_to_download.txt -P data/ezquake

      - name: Parse variables
        run: (cd data/ezquake && python parse_variables.py)

      - name: Delete obsolete files
        run: rm data/ezquake/help_variables.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit updated help files (if changed)
        with:
          commit_message: Update ezQuake help files.
          file_pattern: data/ezquake/*.json
